### ISSUE TITLE
Create template for project

### ISSUE THREAD

**Issue by JorgeRFM** [Rodoba96/daw-project-crypto#1]
Create the template for the project for all other recourses to use

**Comment by Rodoba96** [comment]
[project mock-up.pdf](https://github.com/Rodoba96/daw-project-crypto/files/7149803/project.mock-up.pdf)

**Comment by Rodoba96** [comment]
![File_000 (1)](https://user-images.githubusercontent.com/88676178/132993175-bff54718-6997-4c90-abeb-ae8680d74ac5.png)
